### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by Chitresh-code** [Chitresh-code/DSA_Worksheet#1]
❗**Write Code in Only One Language** (CPP, C, Java, Python)
## **Give File Name : Selection_Sort** ✅ In respective language folder

#📑 **DESCRIPTION**

### Selection Sort

![Difficulty](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

**Problem Statement** 
Sort any given unsorted array of size n in ascending order using the selection sort algorithm.

**Example**
```
Input :
n = 5
arr = [8, 6, 2, 5, 1]

Output :
1 2 5 6 8
```

**Sample Input 1**
```
6
2 13 4 1 3 6
```

**Sample Output 1**
```
1 2 3 4 6 13
```

**Sample Input 2**
```
5
9 3 6 2 0
```

**Sample Output 2**
```
0 2 3 6 9
```

**Constraints**
```
1 <= N <= 10^3
0 <= arr[i] <= 10^5
Time Limit: 1 sec
```

[Problem](https://www.codingninjas.com/studio/problems/selection-sort_624469?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf)

**Comment by UdaySagar-Git** [comment]
hey @Chitresh-code @lilmistake  I would like to work on this , can you please assign it to me

**Comment by gitaditee** [comment]
@Chitresh-code can you please assign this work to me I want to contribute

**Comment by Chitresh-code** [comment]
@gitaditee if you can code in java or c you can do it as the solutions in Python and C++ are already merged.

Assigning it to you.

**Comment by gitaditee** [comment]
@Chitresh-code yes sure I"ll do  and can you assigned me for others repo also

**Comment by Chitresh-code** [comment]
@gitaditee I am only maintaining this repo for Hacktoberfest, but if you want to you can follow me as I regularly upload issues with DSA questions in this repository.
You can solve them

**Comment by gitaditee** [comment]
Ok I'll follow your profile,, I have  submitted a pull request can you please check @Chitresh-code and I'll be grateful if you merge it because as a it's my first contribution.

**Comment by lilmistake** [comment]
I can't see one by you, make sure you submitted the PR; please link it here as well.

**Comment by gitaditee** [comment]
https://github.com/gitaditee/DSA_Worksheet @lilmistake check if you can see

**Comment by gitaditee** [comment]
Yes I have submmited its also showing on my hacktoberfest account

**Comment by lilmistake** [comment]
Looks like you created a PR for your repo and merged it as well. 
Go to https://github.com/Chitresh-code/DSA_Worksheet and see if you find an option that says something along the lines of "recent changes in XYZ create pull request". Click on the button and create a PR from there.

**Comment by gitaditee** [comment]
Now check if you can see?
@lilmistake

**Comment by gitaditee** [comment]
can you tell me why you have not accepted?
I'll correct the issue @lilmistake

**Comment by lilmistake** [comment]
I'll merge your PR on verifying the result or let you know if changes are required, thanks for contributing!

**Comment by gitaditee** [comment]
Sure thanks please inform me if any changes are required
@lilmistake

**Comment by Dev-Abhay01** [comment]
@Chitresh-code can you please assign this work to me I want to contribute
