### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by Akash7649** [Chitresh-code/DSA_Worksheet#20]
Hey @Chitresh-code I would like to contribute to the program of sieve of Eratosthenes that finds all the prime numbers from 1 to n in O(n*log(log(n)) time complexity. 
So please assign me this issue under the label of Hacktoberfest2023

**Comment by Dev-Abhay01** [comment]
i want to contribute @Chitresh-code 
please assign me this issue..

**Comment by yanurag1414** [comment]
Please assign me this issue

**Comment by Chitresh-code** [comment]
Hey @swarupsahu08 you can contribute in any other issue.. as this issue is not a DSA question and also not properly written

**Comment by Chitresh-code** [comment]
@swarupsahu08 Message on [this issue](https://github.com/Chitresh-code/DSA_Worksheet/issues/11) so I can assign it to you.
