### ISSUE TITLE
Sort 0 1 2

### ISSUE THREAD

**Issue by Chitresh-code** [Chitresh-code/DSA_Worksheet#24]
❗**Write Code in Only One Language** (CPP, C, Java, Python)

## Give File Name : Sort012 ✅ In respective language folder

# 📑 DESCRIPTION

### Sort 0 1 2

![Difficulty](https://img.shields.io/badge/Difficulty-Medium-brightgreen)

**Problem Statement:** 
Given an array consisting of only 0s, 1s, and 2s. Write a program to in-place sort the array without using inbuilt sort functions. 

**Note:**
Try to solve the problem in 'Single Scan'. ' Single Scan' refers to iterating over the array/list just once or to put it in other words, you will be visiting each element in the array/list just once.

**Input Format:**
```
The first line contains an integer 'T' which denotes the number of test cases or queries to be run. Then the test cases follow.

The first line of each test case contains an Integer 'N' denoting the size of the array/list.

The second line of each test case contains 'N' space-separated Integers denoting the array/list.
```
**Output Format:**
```
For each test case/query, print the sorted array/list(ARR) as space-separated Integers.

Output for every test case will be printed in a separate line.
```

**Example**
```
Input :
T = 2
N = 6
arr1 = [0, 1, 2, 2, 1, 0]
N = 7
arr1 = [0, 1, 2, 1, 2, 1, 2]

Output :
0 0 1 1 2 2
0 1 1 1 2 2 2
```

**Sample Input 1**
```
2
6
0 1 2 2 1 0
7
0 1 2 1 2 1 2
```

**Sample Output 1**
```
0 0 1 1 2 2
0 1 1 1 2 2 2
```

**Sample Input 2**
```
2
7
2 2 2 1 1 1 0
6
2 1 2 0 1 0
```

**Sample Output 2**
```
0 1 1 1 2 2 2
0 0 1 1 2 2
```

**Constraints**
```
1 <= T <= 10
1 <= N <= (5 * (10 ^ 5))
0 <= ARR[i] <= 2

Where 'N' is the size of the given array/list.
And, ARR[i] denotes the i-th element in the array/list.

Time Limit: 1sec 
```

[Problem](https://www.codingninjas.com/studio/problems/631055?topList=striver-sde-sheet-problems&utm_source=striver&utm_medium=website&leftPanelTab=0)

**Comment by yanurag1414** [comment]
please Assign this to me

**Comment by yanurag1414** [comment]
Please assign this to me
