### ISSUE TITLE
Changes in README and CONTRIBUTING files

### ISSUE THREAD

**Issue by Chitresh-code** [Chitresh-code/DSA_Worksheet#25]
I want to add the names and GitHub profiles of everyone who has created an issue or merged a pull request in this repository, (basically any contribution) in the [Our Contributors](https://github.com/Chitresh-code/DSA_Worksheet#our-%EF%B8%8F-contributors) section in the [README](https://github.com/Chitresh-code/DSA_Worksheet/blob/main/README.md).

Also I want to add clear and easy to understand instructions (maybe a video guide) on how to contribute in the [CONTRIBUTING](https://github.com/Chitresh-code/DSA_Worksheet/blob/main/CONTRIBUTING.md) file and what issues and pull requests will be accepted.
I also want to add the instructions on the correct format of writing an issue. which I will attach here.
[Issue_Template.md](https://github.com/Chitresh-code/DSA_Worksheet/files/12935241/Issue_Template.md)

You can also check the issues posted by me @Chitresh-code for reference.

**Comment by Anup2601** [comment]
I am excited to work on it

https://1drv.ms/w/c/223a14c9189abe49/EcJA1rStwxlMn69f_gJCBDkBs0PYBMe3SwrVmhKEPxboLg?e=ahgrzQ

**Comment by ayushtiwari1405** [comment]
Hello👋, I would like to contribute to this project
