### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by BEAST-PRINCE** [Chitresh-code/DSA_Worksheet#33]
❗**Write Code in Only One Language** (CPP, C, Java, Python)

## Give File Name : <some file name> ✅ In respective language folder

# 📑 DESCRIPTION

### Problem Title

![Difficulty](https://img.shields.io/badge/Difficulty-Level_of_Difficulty-brightgreen)

**Problem Statement:** 
Explain the problem

**Note:**
If any

**Input Format:**
```
Input format here
```
**Output Format:**
```
Output format here
```

**Example**
```
Example

```

**Sample Input 1**
```
Sample input 1
```

**Sample Output 1**
```
Sample output 1
```

**Sample Input 2**
```
Sample input 2
```

**Sample Output 2**
```
Sample output 2
```

**Constraints**
```
Constraints and complexity 
```

[Link of Problem If Copied from Some Site](https://github.com/Chitresh-code/DSA_Worksheet)

**Comment by BEAST-PRINCE** [comment]
Please assign this issue to me.
I've already made a Pr but you rejected it asking me to create an issue for it and then solve it.
Thank you.

**Comment by lilmistake** [comment]
The issue template is supposed to be used as a framework to create the issue.
You need to fill in all the fields and enter all required details to create a valid problem statement. 
Refer to  [CONTRIBUTING.md](https://github.com/Chitresh-code/DSA_Worksheet/blob/main/CONTRIBUTING.md#create-problem-statements) for more details.
