### ISSUE TITLE
Video Guide

### ISSUE THREAD

**Issue by Chitresh-code** [Chitresh-code/DSA_Worksheet#41]
As it is a repository for beginners to get started on Git & GitHub, add a video guide explaining the details of the repository and how to properly merge a valid pull request.

- [ ] Add the video guide in [CONTRIBUTING.md](https://github.com/Chitresh-code/DSA_Worksheet/blob/main/CONTRIBUTING.md)

**Comment by lilmistake** [comment]
Solved with https://github.com/Chitresh-code/DSA_Worksheet/pull/44
