### ISSUE TITLE
Merge Sort (Not assigned correctly

### ISSUE THREAD

**Issue by Ace117MC** [Chitresh-code/DSA_Worksheet#52]

**Comment by prabhat224** [comment]
Please assign me with this

**Comment by Somil-Shukla** [comment]
please assign this issue to me, I can provide c++ solution.

**Comment by Ace117MC** [comment]
I started this so that you could assign this to me. If you wanted separate comment for assignment, you should have mentioned in contribution guidelines

**Comment by lilmistake** [comment]
> I started this so that you could assign this to me.

Not how open sourcing works dummy. If you're working on something you should let it be known. We assumed people would know that, and they do, refer to https://github.com/Chitresh-code/DSA_Worksheet/issues/58

Closing the issue and removing the problem statement earned you nothing but was an inconvenience to all.
