### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by lilmistake** [Chitresh-code/DSA_Worksheet#68]
❗**Write Code in Only One Language** (CPP, C, Java, Python)

## Give File Name : merge_sort ✅ In respective language folder

# 📑 DESCRIPTION

### Merge Sort

![Difficulty](https://img.shields.io/badge/Difficulty-Medium-yellow)

**Problem Statement:** 
Perform Merge Sort Algorithm on the given list of integers

**Input Format:**
```
The first line will contain a single integer - the size of the list
The second line will contain space-separated integers of a given length
```
**Output Format:**
```
Space-separated list of integers
```

**Sample Input 1**
```
5
43 65 12 77 22
```

**Sample Output 1**
```
12 22 43 65 77
```

**Sample Input 2**
```
3
3 2 1
```

**Sample Output 2**
```
1 2 3
```

**Constraints**
```
The length of the list does not exceed 10e6
```

[Merge Sort](https://www.geeksforgeeks.org/merge-sort)

**Comment by 08Uzair** [comment]
Assign this to me

**Comment by Somil-Shukla** [comment]
please assign this issue to me

**Comment by 08Uzair** [comment]
I had done the PR please Check it and give the review

**Comment by AshaHolla** [comment]
I have worked on this before, pls assign me

**Comment by BEAST-PRINCE** [comment]
Please assign me.

**Comment by yashashwini16** [comment]
@lilmistake can you assign this to me , I like to code in python

**Comment by 08Uzair** [comment]
[lilmistake](https://github.com/lilmistake) i had done the PR please check it

**Comment by AnuragDhavale** [comment]
@BEAST-PRINCE I would like to work on it, please assign me

**Comment by BEAST-PRINCE** [comment]
> @BEAST-PRINCE I would like to work on it, please assign me

I cannot assign this issue, the owners of the repo are the one that assign issues :)
